import { describe, expect, test } from "bun:test";
import { filterGeneratedDiff } from "../services/GitWorktreeManager.ts";
import { isGeneratedFile } from "./generatedFiles.ts";

describe("generated file detection", () => {
  test("matches generated path patterns from Linguist", () => {
    expect(isGeneratedFile("bun.lock")).toBe(true);
    expect(isGeneratedFile("packages/app/node_modules/react/index.js")).toBe(true);
    expect(isGeneratedFile("src/__generated__/schema.ts")).toBe(true);
    expect(isGeneratedFile("src/components/Button.tsx")).toBe(false);
  });

  test("matches generated headers when patch content includes them", () => {
    expect(
      isGeneratedFile("api/types.go", "// Code generated by mockgen. DO NOT EDIT.\npackage api"),
    ).toBe(true);
    expect(isGeneratedFile("api/types.go", "package api\n")).toBe(false);
  });
});

describe("filterGeneratedDiff", () => {
  test("removes generated file sections from raw patches", () => {
    const raw = [
      "diff --git a/bun.lock b/bun.lock",
      "index 1111111..2222222 100644",
      "--- a/bun.lock",
      "+++ b/bun.lock",
      "@@ -1 +1 @@",
      "-old",
      "+new",
      "diff --git a/src/app.ts b/src/app.ts",
      "index 3333333..4444444 100644",
      "--- a/src/app.ts",
      "+++ b/src/app.ts",
      "@@ -1 +1 @@",
      "-oldApp();",
      "+newApp();",
    ].join("\n");

    const filtered = filterGeneratedDiff(raw);

    expect(filtered).not.toContain("bun.lock");
    expect(filtered).toContain("src/app.ts");
    expect(filtered).toContain("+newApp();");
  });
});
