const XCODE_EXTENSIONS = new Set([".nib", ".xcworkspacedata", ".xcuserstate"]);
const MAYBE_MINIFIED_EXTENSIONS = new Set([".js", ".css"]);
const SOURCE_MAP_EXTENSIONS = [".css.map", ".js.map"];
const PROTOBUF_EXTENSIONS = new Set([".py", ".java", ".h", ".cc", ".cpp", ".m", ".rb", ".php"]);
const APACHE_THRIFT_EXTENSIONS = new Set([
  ".rb",
  ".py",
  ".go",
  ".js",
  ".m",
  ".java",
  ".h",
  ".cc",
  ".cpp",
  ".php",
]);
const HAXE_EXTENSIONS = new Set([".js", ".py", ".lua", ".cpp", ".h", ".java", ".cs", ".php"]);
const HTML_EXTENSIONS = new Set([".html", ".htm", ".xhtml"]);

const GENERATED_PATH_PATTERNS = [
  /(?:^|\/)\.idea\//,
  /(^Pods|\/Pods)\//,
  /(^|\/)Carthage\/Build\//,
  /\.designer\.(cs|vb)$/i,
  /\.feature\.cs$/i,
  /node_modules\//,
  /vendor\/((?!-)[-0-9A-Za-z]+(?<!-)\.)+(com|edu|gov|in|me|net|org|fm|io)/,
  /(Gopkg|glide)\.lock/,
  /Package\.resolved/,
  /poetry\.lock/,
  /pdm\.lock/,
  /uv\.lock/,
  /pixi\.lock/,
  /(^|\/)(\w+\.)?esy\.lock$/,
  /deno\.lock/,
  /npm-shrinkwrap\.json/,
  /package-lock\.json/,
  /pnpm-lock\.yaml/,
  /(?:^|\/)bun\.lockb?$/,
  /(^|\/)\.pnp\..*$/,
  /Godeps\//,
  /composer\.lock/,
  /.\.zep\.(?:c|h|php)$/,
  /Cargo\.lock/,
  /Cargo\.toml\.orig/,
  /(^|\/)flake\.lock$/,
  /(^|\/)MODULE\.bazel\.lock$/,
  /(?:^|\/)gradlew(?:\.bat)?$/i,
  /(?:^|\/)mvnw(?:\.cmd)?$/i,
  /Pipfile\.lock/,
  /(?:^|\/)\.terraform\.lock\.hcl$/,
  /__generated__\//,
  /_tlb\.pas$/i,
  /(?:^|\/)htmlcov\//,
  /(?:^|\/)\.sqlx\/query-[a-f\d]{64}\.json$/,
];

export function isGeneratedFile(path: string, content = ""): boolean {
  const normalizedPath = path.replace(/\\/g, "/");
  const extension = extname(normalizedPath);
  const lowercaseExtension = extension.toLowerCase();
  const lines = content ? content.split("\n") : [];

  // Ported from github-linguist/linguist lib/linguist/generated.rb.
  return (
    XCODE_EXTENSIONS.has(extension) ||
    GENERATED_PATH_PATTERNS.some((pattern) => pattern.test(normalizedPath)) ||
    isMinifiedFile(lowercaseExtension, lines) ||
    hasSourceMap(lowercaseExtension, lines) ||
    isSourceMap(normalizedPath, lowercaseExtension, lines) ||
    isGeneratedByPathOrHeader(normalizedPath, extension, lowercaseExtension, lines)
  );
}

function extname(path: string): string {
  const basename = path.split("/").pop() ?? path;
  const dotIndex = basename.lastIndexOf(".");
  return dotIndex > 0 ? basename.slice(dotIndex) : "";
}

function isMinifiedFile(extension: string, lines: string[]): boolean {
  if (!MAYBE_MINIFIED_EXTENSIONS.has(extension) || lines.length === 0) return false;

  const totalLength = lines.reduce((sum, line) => sum + line.length, 0);
  return totalLength / lines.length > 110;
}

function hasSourceMap(extension: string, lines: string[]): boolean {
  if (!MAYBE_MINIFIED_EXTENSIONS.has(extension)) return false;

  return lines.slice(-2).some((line) => /^\/[*/][#@] source(?:Mapping)?URL|sourceURL=/.test(line));
}

function isSourceMap(path: string, extension: string, lines: string[]): boolean {
  if (extension !== ".map") return false;

  return (
    SOURCE_MAP_EXTENSIONS.some((suffix) => path.toLowerCase().endsWith(suffix)) ||
    /^{"version":\d+,/.test(lines[0] ?? "") ||
    (lines[0] ?? "").startsWith("/** Begin line maps. **/{")
  );
}

function isGeneratedByPathOrHeader(
  path: string,
  extension: string,
  lowercaseExtension: string,
  lines: string[],
): boolean {
  if (extension === ".js" && lines.length > 0) {
    if ((lines[0] ?? "").startsWith("// Generated by ")) return true;

    if (
      lines[0] === "(function() {" &&
      (lines[lines.length - 2] ?? "") === "}).call(this);" &&
      (lines[lines.length - 1] ?? "") === ""
    ) {
      let score = 0;
      for (const line of lines) {
        if (line.includes("var ")) {
          score += (line.match(/_fn|_i|_len|_ref|_results/g) ?? []).length;
          score += 3 * (line.match(/__bind|__extends|__hasProp|__indexOf|__slice/g) ?? []).length;
        }
      }
      if (score >= 3) return true;
    }
  }

  if (
    extension === ".js" &&
    lines.length >= 5 &&
    /^(?:[^/]|\/[^*])*\/\*(?:[^*]|\*[^/])*Generated by PEG\.js/.test(lines.slice(0, 5).join(""))
  ) {
    return true;
  }

  if (
    lowercaseExtension === ".xml" &&
    lines.length > 3 &&
    (lines[1] ?? "").includes("<doc>") &&
    (lines[2] ?? "").includes("<assembly>") &&
    (lines[lines.length - 2] ?? "").includes("</doc>")
  ) {
    return true;
  }

  if ([".ps", ".eps", ".pfa"].includes(lowercaseExtension) && lines.length > 0) {
    if (/^\s*(?:currentfile eexec\s+|\/sfnts\s+\[\s<)/m.test(lines.join("\n"))) return true;
    const creatorLine = lines.slice(0, 10).find((l) => l.startsWith("%%Creator: "));
    if (creatorLine) {
      if (
        /[0-9]|draw|mpage|ImageMagick|inkscape|MATLAB|PCBNEW|pnmtops|\(Unknown\)|Serif Affinity|Filterimage -tops/.test(
          creatorLine,
        )
      ) {
        return true;
      }
      if (
        creatorLine.includes("EAGLE") &&
        lines.slice(0, 5).some((l) => l.startsWith("%%Title: EAGLE Drawing "))
      ) {
        return true;
      }
    }
  }

  if (
    extension === ".go" &&
    lines.slice(0, 40).some((line) => /^\/\/ Code generated .*/.test(line))
  ) {
    return true;
  }

  if (
    extension === ".proto" &&
    lines
      .slice(0, 20)
      .some((line) => line.includes("This file was autogenerated by go-to-protobuf"))
  ) {
    return true;
  }

  if (
    PROTOBUF_EXTENSIONS.has(extension) &&
    lines
      .slice(0, 3)
      .some((line) => line.includes("Generated by the protocol buffer compiler.  DO NOT EDIT!"))
  ) {
    return true;
  }

  if (extension === ".js" && (lines[5] ?? "").includes("GENERATED CODE -- DO NOT EDIT!")) {
    return true;
  }

  if (
    extension === ".ts" &&
    (lines[0] ?? "").includes("Code generated by protoc-gen-ts_proto. DO NOT EDIT.")
  ) {
    return true;
  }

  if (
    APACHE_THRIFT_EXTENSIONS.has(extension) &&
    lines.slice(0, 6).some((line) => line.includes("Autogenerated by Thrift Compiler"))
  ) {
    return true;
  }

  if (
    extension === ".h" &&
    (lines[0] ?? "").includes("/* DO NOT EDIT THIS FILE - it is machine generated */") &&
    (lines[1] ?? "").includes("#include <jni.h>")
  ) {
    return true;
  }

  if (extension === ".yml" && (lines[lines.length - 2] ?? "").includes("recorded_with: VCR")) {
    return true;
  }

  if (extension === ".g" && (lines[1] ?? "").includes("generated by Xtest")) {
    return true;
  }

  if (
    (extension === ".c" || extension === ".cpp") &&
    (lines[0] ?? "").includes("Generated by Cython")
  ) {
    return true;
  }

  if (
    extension === ".mod" &&
    ((lines[0] ?? "").includes("PCBNEW-LibModule-V") ||
      (lines[0] ?? "").includes("GFORTRAN module version '"))
  ) {
    return true;
  }

  if (extension === ".meta" && (lines[0] ?? "").includes("fileFormatVersion: ")) {
    return true;
  }

  if (
    extension === ".rb" &&
    (lines[2] ?? "").startsWith("# This file is automatically generated by Racc")
  ) {
    return true;
  }

  if (
    extension === ".java" &&
    (lines[0] ?? "").startsWith("/* The following code was generated by JFlex ")
  ) {
    return true;
  }

  if (
    extension === ".java" &&
    (lines[0] ?? "").startsWith("// This is a generated file. Not intended for manual editing.")
  ) {
    return true;
  }

  if (
    extension === ".Rd" &&
    (lines[0] ?? "").includes("% Generated by roxygen2: do not edit by hand")
  ) {
    return true;
  }

  if (
    extension === ".js" &&
    ((lines[0] ?? "").startsWith("/* parser generated by jison ") ||
      (lines[0] ?? "").startsWith("/* generated by jison-lex "))
  ) {
    return true;
  }

  if (
    [".cpp", ".hpp", ".h", ".cc"].includes(extension) &&
    (lines[0] ?? "").startsWith("// Generated by the gRPC")
  ) {
    return true;
  }

  if (
    extension === ".dart" &&
    lines.slice(0, 3).some((line) => line.toLowerCase().match(/generated code\W{2,3}do not modify/))
  ) {
    return true;
  }

  if (
    path.endsWith("ppport.h") &&
    (lines[8] ?? "").includes("Automatically created by Devel::PPPort")
  ) {
    return true;
  }

  if (
    (extension === ".yy" || extension === ".yyp") &&
    (/^\s*[{[]/.test(lines.slice(0, 3).join("")) || /^\d\.\d\.\d.+\|{/.test(lines[0] ?? ""))
  ) {
    return true;
  }

  if (
    (extension === ".c" || extension === ".h") &&
    (/^\/\* GIMP [a-zA-Z0-9- ]+ C-Source image dump \(.+?\.c\) \*\//.test(lines[0] ?? "") ||
      /^\/\*  GIMP header image file format \([a-zA-Z0-9- ]+\): .+?\.h  \*\//.test(lines[0] ?? ""))
  ) {
    return true;
  }

  if (
    lowercaseExtension === ".dsp" &&
    lines
      .slice(0, 3)
      .some((line) => line.includes("# Microsoft Developer Studio Generated Build File"))
  ) {
    return true;
  }

  if (
    HAXE_EXTENSIONS.has(extension) &&
    lines.slice(0, 3).some((line) => line.includes("Generated by Haxe"))
  ) {
    return true;
  }

  if (isGeneratedHtml(lowercaseExtension, lines)) {
    return true;
  }

  if (
    lowercaseExtension === ".java" &&
    lines.slice(0, 2).some((line) => line.includes("This file is generated by jOOQ."))
  ) {
    return true;
  }

  if (
    lowercaseExtension === ".rbi" &&
    (lines[0] ?? "").startsWith("# typed:") &&
    (lines[2] ?? "").includes("DO NOT EDIT MANUALLY") &&
    /^# Please (run|instead update this file by running) `bin\/tapioca/.test(lines[4] ?? "")
  ) {
    return true;
  }

  return lowercaseExtension === ".frm" && (lines[0] ?? "").includes("TYPE=VIEW");
}

function isGeneratedHtml(extension: string, lines: string[]): boolean {
  if (!HTML_EXTENSIONS.has(extension)) return false;

  return (
    lines
      .slice(0, 2)
      .some((line) => line.includes("<!-- Generated by pkgdown: do not edit by hand -->")) ||
    (lines.length > 2 &&
      (lines[2] ?? "").startsWith("<!-- This is an automatically generated file.")) ||
    lines.slice(0, 31).some((line) => /<!--\s+Generated by Doxygen\s+[.0-9]+\s*-->/i.test(line)) ||
    /<meta\s+[^>]*(name|content|value)=["']?(org\s+mode|j?latex2html|groff|makeinfo|texi2html|ronn)\b/i.test(
      lines.slice(0, 31).join(" "),
    )
  );
}
